apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hon-flyingfish-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hon-flyingfish-go 
  name: hon-flyingfish-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hon-flyingfish-go 
